apiVersion: 1
datasources:
  - name: PostgreSQL_Liquidity
    type: postgres
    url: postgres_ts:5432
    user: ts_admin
    secureJsonData:
      password: ts_password
    jsonData:
      database: liquidity_warehouse
      sslmode: disable
