apiVersion: 1
datasources:
  - name: PostgreSQL_Liquidity
    type: postgres
    url: postgres_dw:5432
    user: dw_admin
    secureJsonData:
      password: dw_password
    jsonData:
      database: liquidity_dw
      sslmode: disable
